// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDVB0iRGThx5OGu_gBfA3eKijMTvtYmFI',
    appId: '1:337394996429:android:d7307697ba666647384584',
    messagingSenderId: '337394996429',
    projectId: 'rhcd-d76a2',
    storageBucket: 'rhcd-d76a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHZ6ras-EhvkPPQuHuzN_v71lbXnuzr6o',
    appId: '1:337394996429:ios:a21373f05a110514384584',
    messagingSenderId: '337394996429',
    projectId: 'rhcd-d76a2',
    storageBucket: 'rhcd-d76a2.appspot.com',
    iosClientId: '337394996429-1oso45777c6h1aa0d3klin3ogpcssdpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.rhc',
  );
}
